// SPDX-FileCopyrightText: © 2025 Phala Network <dstack@phala.network>
//
// SPDX-License-Identifier: BUSL-1.1

//! Materialise the dstack-kms key set from the platform-provided root.
//!
//! The platform holds each user's root key material (P-256 root CA key +
//! secp256k1 identity key) and ships it through the courier channel. The KMS
//! core itself is unmodified: it expects a fully-bootstrapped key set on disk
//! under `cert_dir` and, when those files exist, skips onboarding and serves
//! directly (`kms/src/main.rs` / `config.rs::keys_exists`).
//!
//! So instead of the KMS bootstrapping its own root in-TEE, the sidecar writes
//! the exact files the KMS loads, using the same `ra-tls`/`rcgen` primitives
//! the KMS uses so the formats match byte-for-byte:
//!
//!   tmp-ca.{crt,key}  root-ca.{crt,key}  rpc.{crt,key}  root-k256.key  rpc-domain
//!
//! `root-ca.key` MUST be P-256 — the KMS KDF extracts the P-256 scalar from it
//! to derive every app/disk/env key (`ra-tls/src/kdf.rs`).

use anyhow::{Context, Result};
use base64::{engine::general_purpose::STANDARD, Engine};
use k256::ecdsa::SigningKey;
use ra_tls::cert::CertRequest;
use ra_tls::rcgen::{KeyPair, PKCS_ECDSA_P256_SHA256};
use serde::Deserialize;
use std::path::Path;

/// The unsealed root payload the platform sends via `sealed_root`.
#[derive(Deserialize)]
pub struct RootMaterial {
    #[allow(dead_code)]
    pub v: u32,
    /// P-256 (prime256v1) PKCS#8 PEM — becomes `root-ca.key`, the KDF root.
    pub root_ca_key: String,
    /// secp256k1 32-byte big-endian scalar, base64 — becomes `root-k256.key`.
    pub k256_key: String,
    /// RPC cert subject / SAN (the KMS RPC domain).
    #[serde(default = "default_domain")]
    pub domain: String,
}

fn default_domain() -> String {
    "kms.local".to_string()
}

/// Parse the unsealed root payload (JSON bytes from `unseal_root`).
pub fn parse_root_material(root_bytes: &[u8]) -> Result<RootMaterial> {
    serde_json::from_slice(root_bytes).context("failed to parse root material JSON")
}

/// Build the full dstack-kms key set from the platform root and write the
/// files the KMS expects into `cert_dir` (`<kms_volume>/certs`).
///
/// Mirrors `kms/src/onboard_service.rs::Keys::{from_keys,store}` but takes the
/// root CA key + k256 key from the platform instead of generating them, and
/// skips the RA-TLS attestation on the rpc cert (regenerated by the KMS's own
/// `update_certs` on boot; its attestation failure there is non-fatal).
pub fn install_kms_keyset(cert_dir: &Path, m: &RootMaterial) -> Result<()> {
    std::fs::create_dir_all(cert_dir)
        .with_context(|| format!("failed to create cert dir {}", cert_dir.display()))?;

    let domain = m.domain.as_str();

    // platform-controlled roots
    let ca_key = KeyPair::from_pem(&m.root_ca_key)
        .context("failed to parse root_ca_key (expect P-256 PKCS#8 PEM)")?;
    let k256_bytes = STANDARD
        .decode(m.k256_key.trim())
        .context("failed to base64-decode k256_key")?;
    let k256_key = SigningKey::from_slice(&k256_bytes).context("invalid k256_key bytes")?;

    // leaf material — regenerated here; re-signable from the root on any DR
    let tmp_ca_key = KeyPair::generate_for(&PKCS_ECDSA_P256_SHA256)?;
    let rpc_key = KeyPair::generate_for(&PKCS_ECDSA_P256_SHA256)?;

    // certs — structure must match what the KMS produced for itself
    let tmp_ca_cert = CertRequest::builder()
        .org_name("Dstack")
        .subject("Dstack Client Temp CA")
        .ca_level(0)
        .key(&tmp_ca_key)
        .build()
        .self_signed()
        .context("failed to self-sign tmp CA cert")?;

    let ca_cert = CertRequest::builder()
        .org_name("Dstack")
        .subject("Dstack KMS CA")
        .ca_level(1)
        .key(&ca_key)
        .build()
        .self_signed()
        .context("failed to self-sign root CA cert")?;

    let alt_names = [domain.to_string()];
    let rpc_cert = CertRequest::builder()
        .subject(domain)
        .alt_names(&alt_names)
        .special_usage("kms:rpc")
        .key(&rpc_key)
        .build()
        .signed_by(&ca_cert, &ca_key)
        .context("failed to sign rpc cert")?;

    write(cert_dir, "tmp-ca.key", tmp_ca_key.serialize_pem().as_bytes())?;
    write(cert_dir, "tmp-ca.crt", tmp_ca_cert.pem().as_bytes())?;
    write(cert_dir, "root-ca.key", ca_key.serialize_pem().as_bytes())?;
    write(cert_dir, "root-ca.crt", ca_cert.pem().as_bytes())?;
    write(cert_dir, "rpc.key", rpc_key.serialize_pem().as_bytes())?;
    write(cert_dir, "rpc.crt", rpc_cert.pem().as_bytes())?;
    write(cert_dir, "root-k256.key", k256_key.to_bytes().as_slice())?;
    write(cert_dir, "rpc-domain", domain.as_bytes())?;

    tracing::info!(
        "courier install: materialised dstack-kms key set in {}",
        cert_dir.display()
    );
    Ok(())
}

fn write(dir: &Path, name: &str, bytes: &[u8]) -> Result<()> {
    let path = dir.join(name);
    std::fs::write(&path, bytes).with_context(|| format!("failed to write {}", path.display()))?;
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use ra_tls::cert::CaCert;
    use ra_tls::kdf;

    /// The installed key set must be loadable by the *exact* primitives the KMS
    /// core uses on boot: `CaCert::load` for the root CA and `kdf` for key
    /// derivation. If this passes, the KMS will accept our files and serve.
    #[test]
    fn keyset_is_kms_loadable() {
        // platform side: P-256 root CA key (PKCS#8 PEM) + secp256k1 32 bytes
        let root_ca_key = KeyPair::generate_for(&PKCS_ECDSA_P256_SHA256).unwrap();
        let root_ca_key_pem = root_ca_key.serialize_pem();
        let k256 = SigningKey::random(&mut rand::rngs::OsRng);
        let k256_b64 = STANDARD.encode(k256.to_bytes().as_slice());

        let m = RootMaterial {
            v: 1,
            root_ca_key: root_ca_key_pem,
            k256_key: k256_b64,
            domain: "kms.local".to_string(),
        };

        let dir = std::env::temp_dir().join(format!("kb-keyset-test-{}", std::process::id()));
        let cert_dir = dir.join("certs");
        install_kms_keyset(&cert_dir, &m).unwrap();

        // every file the KMS `keys_exists()` checks
        for f in [
            "tmp-ca.crt",
            "tmp-ca.key",
            "root-ca.crt",
            "root-ca.key",
            "rpc.crt",
            "rpc.key",
            "root-k256.key",
        ] {
            assert!(cert_dir.join(f).exists(), "missing {f}");
        }

        // KMS loads the root CA exactly this way (main_service.rs)
        let ca = CaCert::load(cert_dir.join("root-ca.crt"), cert_dir.join("root-ca.key")).unwrap();
        // ...and derives app keys from it exactly this way (main_service.rs)
        kdf::derive_p256_key_pair(&ca.key, &[b"app-id", b"app-key"]).unwrap();
        kdf::derive_dh_secret(&ca.key, &[b"app-id", b"env-encrypt-key"]).unwrap();

        // k256 identity key round-trips
        let raw = std::fs::read(cert_dir.join("root-k256.key")).unwrap();
        SigningKey::from_slice(&raw).unwrap();

        std::fs::remove_dir_all(&dir).ok();
    }
}
